### ISSUE TITLE
Babel is referenced but not used!

### ISSUE THREAD

**Issue by wenbolovesnz** [cameronjroe/angular-movie-search#1]
Trying to started to make an app with es6 with angular, found your tutorial and this project, but I couldn't see the place you compile your es6 code to es5 with babel in your gulpfile.js

**Comment by ninjasort** [comment]
Hi @wenbolovesnz, I'm actually using the `babelify` transform for browserify in the [package.json](https://github.com/cameronjroe/angular-movie-search/blob/master/package.json#L36)
